width = float(input("가로:"))
length = float(input("세로:"))
height = float(input("높이:"))
volume = width * length * height
print("가로:",width)
print("세로:",length)
print("높이:",height)
print("박스의 부피는",volume, end='') 
print("입니다")
print(" 너무 어렵네")